---
title: "Statistical Models"
subtitle: "Lecture 3"
from: markdown+emoji
author: 
    - name: Dr. Silvio Fanzon
      id: sf
      email: S.Fanzon@hull.ac.uk
      url: https://www.silviofanzon.com
      affiliations: University of Hull
---



::: {.content-hidden}
$
{{< include macros.tex >}}
$
:::


# Lecture 3: <br>Random samples{background-color="#cc0164" visibility="uncounted"}

::: footer

<div color="#cc0164">  </div>

:::





## Outline of Lecture 3

4. Hypothesis testing








# Part 6: <br>Hypothesis testing{background-color="#cc0164" visibility="uncounted"}

::: footer

<div color="#cc0164">  </div>

:::



## Hypothesis testing {.smaller}
### Definition of Hypothesis


- **Idea**:
  * Interested in knowing a population parameter $\theta$
  * $\theta$ cannot be measured directly
  * We can sample the population and draw conclusions on $\theta$
  * Such conclusions are **hypotheses**


::: Definition

A **hypothesis** is a statement about a population parameter

:::




## Hypothesis testing {.smaller}
### Complementary hypotheses


- Two hypotheses are **complementary** if exactly one of them can be true

- Complementary hypotheses are called:
    * $H_0$ the **null hypothesis** 
    * $H_1$ the **alternative hypothesis**

- **Goal**: Find a way to decide which between $H_0$ and $H_1$ is true




## Hypothesis testing {.smaller}
### How to model hypotheses

We denote by:

- $\theta$ a population parameter
- $\Theta$ the space of all population parameters

For $\Theta_0 \subset \Theta$ we define the associated 
null and alternative hypotheses as
\begin{align*}
H_0 \colon & \theta \in \Theta_0  & \qquad \text{ null hypothesis} \\
H_1 \colon & \theta \in \Theta_0^c  & \qquad \text{ alternative hypothesis}
\end{align*}





## Hypothesis testing {.smaller}
### Definition of Hypothesis test


::: Definition

A **hypothesis test** is a rule to decide:

- For which sample values we decide to **accept** $H_0$ as true
- For which sample values we **reject** $H_0$ and accept $H_1$ as true

:::


## Hypothesis testing {.smaller}
### Acceptance and Critical regions

The sample space is partitioned into two regions:

- **Acceptance region:** For samples $\XX$ in this region we **accept** $H_0$
- **Critical region:** For samples $\XX$ in this region we **reject** $H_0$

**In most cases:** Critical region is defined in terms of a statistic $W(\XX)$


**Example**: We could decide to reject $H_0$ if 
$$
W(\XX) \in R
$$ 
with $R \subset \R$ some rejection region



## Hypothesis testing {.smaller}
### One-sided vs Two-sided Tests

Let $\theta$ be one dimensional parameter. A hypothesis test is:

- **One-sided** if the null hypotheses are of the form
  $$ 
  H_0 \colon \theta \leq \theta_0 
  \qquad 
  \text{ or } 
  \qquad 
  H_0 \colon \theta \geq \theta_0 
  $$
  with corresponding one-sided alternative hypotheses
  $$ 
  H_1 \colon \theta > \theta_0 
  \qquad 
  \text{ or } 
  \qquad 
  H_1 \colon \theta < \theta_0 
  $$

- **Two-sided** if the null and alternative hypotheses are of the form
  $$ 
  H_0 \colon \theta = \theta_0  \qquad   
  \text{ and } \qquad 
  H_1 \colon \theta \neq \theta_0 
  $$



## Hypothesis testing {.smaller}
### Philosophical issues

- $H_0$ is usually a **conservative hypothesis**
- If a test indicates to **reject** $H_0$, people do that happily and accept $H_1$
- If a test indicates to **accept** $H_0$ there are issues:
    * Some people like to reject $H_1$ and accept $H_0$
    * Some people like to reject $H_1$, but do not believe fully in $H_0$. They would like to reject $H_0$, but do not have enough evidence to do so

- **Our position:** We do not care, and we either
    * decide in favor of $H_0$ - or **accept** $H_0$
    * decide in favor of $H_1$ - or **accept** $H_1$



## Hypothesis testing {.smaller}
### Example 1 - Two-seded test


The *University of Cottingham Road* wants to advertise its MBA Program: 
$$
\text{ MBA } = \text{ higher salary }
$$

- Is this a true or false statement? 

- The University has only access to incomplete data (could not ask all former students). Need hypothesis testing

- $\theta =$ average change in salary after **completing the MBA program**
  * Null hypothesis: There is no change $\,\, \implies \,\, \theta=0$
  * Alternative hypothesis: There is a change $\,\, \implies \,\, \theta \neq 0$

**Hypothesis test**: 
$\qquad \quad H_0 \colon \theta = 0 \,, \qquad 
H_1 \colon \theta \neq 0$



## Hypothesis testing {.smaller}
### Example 2 - One-sided test


Manager at a *Computer Factory* wants to know the proportion of defective components produced

- Testing is expensive and they can only test a limited sample
- $\theta =$ proportion of defective components
- Manager is happy if $\theta$ is less than some $\theta_0$
- The decision is between:
    * Null hypothesis: Defective components less than $\theta_0$ $\,\, \implies \,\, \theta < \theta_0$
    * Alternative hypothesis: Defective components more than $\theta_0$ $\,\, \implies \,\, \theta \geq \theta_0$

**Hypothesis test**:
$\qquad \quad H_0 \colon \theta < \theta_0 \,, \qquad 
H_1 \colon \theta \geq \theta_0$
 





## References